__default__:
    q:  broad
    h_vmem: 20G
    h_rt:   100:0:0
    pe: smp 1
    binding:    linear:1

AlignAndMarkDuplicates:
    h_vmem:    100G  
    h_rt:    300:00:00
    pe: smp 1
    binding:    linear:1
    
