## Tools Path
gatk_path: /mnt/storage/apps/gatk-4.2.5.0/gatk
java: /usr/bin/java
tabix: /usr/bin/tabix
picard_jar: /home/ma1111/tools/picard.jar
bwa: /usr/bin/bwa
haplocheckCLI_path: /home/mi724/Tools/MitochondriaPipeline/haplocheckCLI/haplocheckCLI.jar

## R Scripts
coverage_script: code/coverage.R

## Parameters
contig_name: "chrM"
coverage_cap: 100000
read_length_for_optimization: 151
max_reads_per_alignment_start: 75
max_alt_allele_count: 4
vaf_filter_threshold: 0

## Path to Reference Files
reference_genome: /mnt/storage/labs/sviswanathan/GATK_ref/Homo_sapiens_assembly38.fasta

## Path to MT Reference Files
mt_ref: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.fasta
mt_ref_index: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.fasta.fai
mt_ref_dict: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.dict
mt_sa: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.fasta.sa
mt_amb: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.fasta.amb
mt_ann: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.fasta.ann
mt_bwt: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.fasta.bwt
mt_pac: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.fasta.pac

## Path to MT Shifted Reference Files
mt_shifted_ann: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.ann
mt_shifted_dict: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.dict
mt_shifted_ref: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta
mt_shifted_sa: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.sa
mt_shifted_bwt: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.bwt
mt_shifted_fai: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.fai
mt_shifted_pac: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.pac
mt_shifted_amb: /mnt/storage/labs/sviswanathan/mt_gs_files/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.amb


shift_back_chain: /mnt/storage/labs/sviswanathan/mt_gs_files/ShiftBack.chain
blacklisted_sites: /mnt/storage/labs/sviswanathan/mt_gs_files/blacklist_sites.hg38.chrM.bed






